# Generated by Django 4.1.6 on 2023-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='category',
            field=models.CharField(choices=[('FE', '프론트엔드'), ('BE', '벡엔드')], default='FE', max_length=10),
        ),
    ]
